// Command docgen regenerates the code-derived reference pages under docs/reference/
// from the actual source: HTTP routes, MCP tool schemas, config structs, and the
// broker-ctl CLI. CI runs `go run ./tools/docgen` and fails if the result differs
// from what is committed (`git diff --exit-code docs/reference`), so the reference
// cannot drift from the code.
//
// Usage: go run ./tools/docgen        (writes docs/reference/*.md)
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/luisgf/ssh-broker/internal/mcpserver"
)

const genBanner = "<!-- GENERATED by tools/docgen — do not edit by hand. Run: make docs-gen -->\n\n"

func main() {
	outDir := "docs/reference"
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fatal(err)
	}
	write(filepath.Join(outDir, "endpoints.md"), genEndpoints())
	write(filepath.Join(outDir, "mcp-tools.md"), genMCPTools())
	write(filepath.Join(outDir, "config.md"), genConfig())
	write(filepath.Join(outDir, "cli.md"), genCLI())
	fmt.Println("docgen: wrote docs/reference/{endpoints,mcp-tools,config,cli}.md")
}

// ── endpoints ────────────────────────────────────────────────────────────────

// services maps a display name to the cmd directory whose main package registers
// the HTTP routes.
var services = []struct{ name, dir string }{
	{"Signer", "cmd/signer"},
	{"Control plane", "cmd/control-plane"},
	{"Broker (HTTP/mTLS)", "cmd/broker"},
	{"MCP HTTP", "cmd/mcp-broker-http"},
}

type route struct{ pattern, handler string }

func genEndpoints() string {
	var b strings.Builder
	b.WriteString(genBanner)
	b.WriteString("# HTTP endpoints\n\nEvery route registered across the services, extracted from the `mux.HandleFunc` / `mux.Handle` calls in the source. See [API reference](../API.md) for request/response bodies and auth.\n")
	for _, svc := range services {
		routes := routesIn(svc.dir)
		if len(routes) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n## %s\n\n`%s`\n\n| Route | Handler |\n|---|---|\n", svc.name, svc.dir)
		for _, r := range routes {
			fmt.Fprintf(&b, "| `%s` | `%s` |\n", r.pattern, mdCell(r.handler))
		}
	}
	return b.String()
}

func routesIn(dir string) []route {
	fset := token.NewFileSet()
	noTests := func(fi os.FileInfo) bool { return !strings.HasSuffix(fi.Name(), "_test.go") }
	pkgs, err := parser.ParseDir(fset, dir, noTests, 0)
	if err != nil {
		fatal(fmt.Errorf("parse %s: %w", dir, err))
	}
	var routes []route
	for _, pkg := range pkgs {
		consts := packageStringConsts(pkg)
		for _, file := range pkg.Files {
			ast.Inspect(file, func(n ast.Node) bool {
				call, ok := n.(*ast.CallExpr)
				if !ok {
					return true
				}
				sel, ok := call.Fun.(*ast.SelectorExpr)
				if !ok || (sel.Sel.Name != "HandleFunc" && sel.Sel.Name != "Handle") || len(call.Args) < 1 {
					return true
				}
				pattern := ""
				switch arg := call.Args[0].(type) {
				case *ast.BasicLit:
					if arg.Kind != token.STRING {
						return true
					}
					if p, err := strconv.Unquote(arg.Value); err == nil {
						pattern = p
					}
				case *ast.Ident:
					pattern = consts[arg.Name] // route named via a package const
				}
				if pattern == "" {
					return true
				}
				handler := ""
				if len(call.Args) >= 2 {
					if _, inline := call.Args[1].(*ast.FuncLit); inline {
						handler = "(inline handler)"
					} else {
						handler = renderExpr(fset, call.Args[1])
					}
				}
				routes = append(routes, route{pattern, handler})
				return true
			})
		}
	}
	sort.Slice(routes, func(i, j int) bool { return routes[i].pattern < routes[j].pattern })
	return routes
}

// packageStringConsts maps package-level string const names to their values, so
// routes registered via a named const (e.g. mux.Handle(prmPath, ...)) resolve.
func packageStringConsts(pkg *ast.Package) map[string]string {
	out := map[string]string{}
	for _, file := range pkg.Files {
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.CONST {
				continue
			}
			for _, spec := range gd.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok || len(vs.Names) != len(vs.Values) {
					continue
				}
				for i, name := range vs.Names {
					if lit, ok := vs.Values[i].(*ast.BasicLit); ok && lit.Kind == token.STRING {
						if v, err := strconv.Unquote(lit.Value); err == nil {
							out[name.Name] = v
						}
					}
				}
			}
		}
	}
	return out
}

// ── MCP tools ────────────────────────────────────────────────────────────────

func genMCPTools() string {
	var b strings.Builder
	b.WriteString(genBanner)
	b.WriteString("# MCP tools\n\nThe tools exposed by the MCP frontends (`cmd/mcp-broker`, `cmd/mcp-broker-http`), with their input schemas — enumerated from the live server (`internal/mcpserver.Register`). See [Tool usage](../USAGE.md) for guidance.\n")

	ctx := context.Background()
	srv := mcp.NewServer(&mcp.Implementation{Name: "ssh-broker", Version: "docgen"}, nil)
	mcpserver.Register(srv, nil, nil) // handlers are not invoked during registration
	st, ct := mcp.NewInMemoryTransports()
	if _, err := srv.Connect(ctx, st, nil); err != nil {
		fatal(fmt.Errorf("server connect: %w", err))
	}
	client := mcp.NewClient(&mcp.Implementation{Name: "docgen", Version: "1"}, nil)
	cs, err := client.Connect(ctx, ct, nil)
	if err != nil {
		fatal(fmt.Errorf("client connect: %w", err))
	}
	defer cs.Close()
	res, err := cs.ListTools(ctx, nil)
	if err != nil {
		fatal(fmt.Errorf("list tools: %w", err))
	}
	tools := res.Tools
	sort.Slice(tools, func(i, j int) bool { return tools[i].Name < tools[j].Name })
	for _, t := range tools {
		fmt.Fprintf(&b, "\n## `%s`\n\n%s\n\n", t.Name, strings.TrimSpace(t.Description))
		for _, p := range schemaProps(t.InputSchema) {
			req := ""
			if p.required {
				req = " *(required)*"
			}
			fmt.Fprintf(&b, "- `%s` (%s)%s — %s\n", p.name, p.typ, req, p.desc)
		}
	}
	return b.String()
}

type prop struct {
	name, typ, desc string
	required        bool
}

// schemaProps best-effort-flattens a JSON-schema object's properties. The SDK
// returns the input schema as a *jsonschema.Schema (server side); marshal it to a
// generic map to stay decoupled from the schema type's exact shape.
func schemaProps(schema any) []prop {
	m := toMap(schema)
	props, _ := m["properties"].(map[string]any)
	if props == nil {
		return nil
	}
	reqSet := map[string]bool{}
	if reqs, ok := m["required"].([]any); ok {
		for _, r := range reqs {
			if s, ok := r.(string); ok {
				reqSet[s] = true
			}
		}
	}
	var out []prop
	for name, raw := range props {
		pm := toMap(raw)
		typ, _ := pm["type"].(string)
		desc, _ := pm["description"].(string)
		out = append(out, prop{name: name, typ: orDash(typ), desc: desc, required: reqSet[name]})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].name < out[j].name })
	return out
}

// ── config ───────────────────────────────────────────────────────────────────

var configStructs = []struct{ file, name, title string }{
	{"internal/broker/engine.go", "Config", "Broker / MCP config (`config.json`)"},
	{"internal/broker/engine.go", "SignerClientConfig", "Broker signer client (`signer`, remote mode)"},
	{"internal/broker/engine.go", "OAuthConfig", "Broker OAuth (`oauth`, `cmd/mcp-broker-http` only)"},
	{"internal/broker/engine.go", "HostConfig", "Broker host (`hosts.<name>`, local mode)"},
	{"internal/ca/loader.go", "CAKeyConfig", "CA key (`ca_keys.<name>`)"},
	{"cmd/signer/main.go", "Config", "Signer config (`signer.json`)"},
	{"cmd/control-plane/main.go", "Config", "Control-plane config (`control-plane.json`)"},
	{"internal/control/behavior.go", "BehaviorConfig", "Control-plane behaviour guardrails (`behavior`)"},
	{"internal/signer/signer.go", "HostPolicy", "Host policy (`hosts.<name>`)"},
	{"internal/signer/cmdpolicy.go", "CommandPolicy", "Command policy (`command_policy`)"},
}

var enumDecls = []struct{ file, title string }{
	{"internal/signer/signer.go", "Role / Purpose"},
	{"internal/signer/cmdpolicy.go", "Command-policy mode"},
}

func genConfig() string {
	var b strings.Builder
	b.WriteString(genBanner)
	b.WriteString("# Config reference\n\nEvery configuration field, extracted from the Go structs (field · JSON key · type · doc comment). See [Operations](../OPERATIONS.md) for worked examples and the `*.example.json` files.\n")
	for _, cs := range configStructs {
		fields := structFields(cs.file, cs.name)
		if len(fields) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n## %s\n\n`%s` in `%s`\n\n| JSON key | Type | Description |\n|---|---|---|\n", cs.title, cs.name, cs.file)
		for _, f := range fields {
			fmt.Fprintf(&b, "| `%s` | `%s` | %s |\n", f.json, f.typ, f.doc)
		}
	}
	b.WriteString("\n## Vocabulary (enumerated constants)\n")
	for _, e := range enumDecls {
		for _, grp := range stringConsts(e.file) {
			fmt.Fprintf(&b, "\n**%s:** %s\n", grp.name, grp.values)
		}
	}
	return b.String()
}

type field struct{ json, typ, doc string }

func structFields(file, name string) []field {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, file, nil, parser.ParseComments)
	if err != nil {
		fatal(fmt.Errorf("parse %s: %w", file, err))
	}
	var out []field
	ast.Inspect(f, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok || ts.Name.Name != name {
			return true
		}
		st, ok := ts.Type.(*ast.StructType)
		if !ok {
			return true
		}
		out = walkStructFields(fset, st, "")
		return false
	})
	return out
}

// walkStructFields flattens a struct's exported fields into doc rows, recursing
// into anonymous nested structs with a dotted key prefix (e.g. `approval.notifier`).
func walkStructFields(fset *token.FileSet, st *ast.StructType, prefix string) []field {
	var out []field
	for _, fl := range st.Fields.List {
		if len(fl.Names) == 0 || !fl.Names[0].IsExported() {
			continue
		}
		jsonKey := fl.Names[0].Name
		if fl.Tag != nil {
			tag := reflect.StructTag(strings.Trim(fl.Tag.Value, "`"))
			if jt := tag.Get("json"); jt != "" {
				k := strings.Split(jt, ",")[0]
				if k == "-" {
					continue // not serialised — internal/computed, not a config key
				}
				if k != "" {
					jsonKey = k
				}
			}
		}
		doc := commentText(fl.Doc)
		if doc == "" {
			doc = commentText(fl.Comment)
		}
		if nested, ok := fl.Type.(*ast.StructType); ok {
			out = append(out, field{json: prefix + jsonKey, typ: "(object)", doc: mdCell(doc)})
			out = append(out, walkStructFields(fset, nested, prefix+jsonKey+".")...)
			continue
		}
		out = append(out, field{json: prefix + jsonKey, typ: mdCell(renderExpr(fset, fl.Type)), doc: mdCell(doc)})
	}
	return out
}

type constGroup struct{ name, values string }

// stringConsts collects each `const (...)` block of typed string assignments into
// a group: the values joined. Used for the policy/role/purpose vocabulary.
func stringConsts(file string) []constGroup {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, file, nil, parser.ParseComments)
	if err != nil {
		fatal(fmt.Errorf("parse %s: %w", file, err))
	}
	var groups []constGroup
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.CONST {
			continue
		}
		var vals []string
		for _, spec := range gd.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok || len(vs.Values) != 1 {
				continue
			}
			lit, ok := vs.Values[0].(*ast.BasicLit)
			if !ok || lit.Kind != token.STRING {
				continue
			}
			if v, err := strconv.Unquote(lit.Value); err == nil && v != "" {
				vals = append(vals, "`"+v+"`")
			}
		}
		if len(vals) >= 2 {
			groups = append(groups, constGroup{name: groupName(gd), values: strings.Join(vals, ", ")})
		}
	}
	return groups
}

func groupName(gd *ast.GenDecl) string {
	if gd.Doc != nil {
		line := strings.SplitN(strings.TrimSpace(gd.Doc.Text()), "\n", 2)[0]
		if len(line) > 60 {
			line = line[:60]
		}
		return line
	}
	return "values"
}

// ── CLI ──────────────────────────────────────────────────────────────────────

func genCLI() string {
	var b strings.Builder
	b.WriteString(genBanner)
	b.WriteString("# broker-ctl CLI\n\nTop-level command reference, captured from `broker-ctl` itself. Run any subcommand with `--help` for its flags.\n\n```\n")
	cmd := exec.Command("go", "run", "./cmd/broker-ctl")
	out, _ := cmd.CombinedOutput() // prints usageTop to stderr and exits non-zero by design
	b.Write(bytes.TrimRight(out, "\n"))
	b.WriteString("\n```\n")
	return b.String()
}

// ── helpers ──────────────────────────────────────────────────────────────────

func renderExpr(fset *token.FileSet, e ast.Expr) string {
	var buf bytes.Buffer
	if err := printer.Fprint(&buf, fset, e); err != nil {
		return ""
	}
	return strings.Join(strings.Fields(buf.String()), " ")
}

func commentText(g *ast.CommentGroup) string {
	if g == nil {
		return ""
	}
	return strings.Join(strings.Fields(g.Text()), " ")
}

func toMap(v any) map[string]any {
	if m, ok := v.(map[string]any); ok {
		return m
	}
	// Fall back via JSON round-trip for typed schema values.
	b, err := json.Marshal(v)
	if err != nil {
		return nil
	}
	var m map[string]any
	if json.Unmarshal(b, &m) != nil {
		return nil
	}
	return m
}

// mdCell makes a string safe inside a Markdown table cell (escape the column
// separator; whitespace is already collapsed by the callers).
func mdCell(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}

func orDash(s string) string {
	if s == "" {
		return "—"
	}
	return s
}

func write(path, content string) {
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "docgen:", err)
	os.Exit(1)
}
